# Generated by Django 2.0.3 on 2018-05-16 21:42

from django.db import migrations, models
import principal.models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mainImage',
            field=models.ImageField(blank=True, default=None, upload_to=principal.models.directory_path_images),
        ),
    ]
