# Generated by Django 2.0.3 on 2018-05-16 22:07

from django.db import migrations, models
import principal.models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_comment_mainimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='mainImage',
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=principal.models.directory_path_images),
        ),
    ]
