# Generated by Django 2.0.7 on 2018-07-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20180516_2207'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Post',
        ),
    ]
