# Generated by Django 2.0.7 on 2018-07-15 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20180715_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='commentText',
            new_name='postText',
        ),
    ]
