# Generated by Django 2.0.7 on 2018-07-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.BigIntegerField(default=0),
        ),
    ]
