# Generated by Django 2.0.7 on 2018-07-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_headerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislike',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
