# Generated by Django 2.0.7 on 2018-08-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_auto_20180731_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentCounter',
            field=models.IntegerField(default=0),
        ),
    ]
